added the stop button
Sanjay8602/Debate-App pull request #5
Opened 2024-04-27 18:28 UTC by Sanjay8602

2024-04-28 06:11 UTC, ogbanugot requested changes

2024-04-28 06:11 UTC, ogbanugot commented on app.py
>          for _i in range(st.session_state.exchange):
you're still using the `exchange` state here. I suggest you use a while loop on the stop condition:
```
while not stop:
     ....
```

2024-04-28 06:11 UTC, ogbanugot commented on app.py
> +                if stop:
this should come immediately under the while loop:
```
while not stop:
     if stop:
          break
```

2024-04-28 06:11 UTC, ogbanugot commented on app.py
> +                if st.session_state.stop_button.button("Stop Interaction"):
move this up as well:
```
while not stop:
     if stop:
          break
     if st.session_state.stop_button.button("Stop Interaction"):
           stop = True
```

2024-04-28 06:11 UTC, ogbanugot commented on app.py
> +                if stop:
remove this duplicate

2024-04-28 06:11 UTC, ogbanugot commented on app.py
> +                if st.session_state.stop_button.button("Stop Interaction"):
remove this duplicate

2024-05-02 08:05 UTC, Sanjay8602 reviewed
updated the stop button

2024-05-02 17:08 UTC, closed without merging